networks:
  pw-service-auth:

services:
  app:
    image: "ghcr.io/petsworld-ltd/pw-service-auth:${TAG}"
    ports:
      - 8080:80
    networks:
      - pw-service-auth
    environment:
      MONGODB_ADDRESS: mongo
      MONGODB_PORT: 27017
      MONGODB_PASS: ${MONGODB_PASS}
      MONGODB_USER: ${MONGODB_USER}

  mongo:
    image: mongo:4.4.19-focal
    restart: always
    networks:
      - pw-service-auth
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - pw-service-auth-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}

#  mongo-express:
#    image: mongo-express:0.54
#    restart: always
#    networks:
#      - pw-service-auth
#    ports:
#      - 8081:8081
#    depends_on:
#      - mongo
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME
#      - ME_CONFIG_MONGODB_ADMINPASSWORD

volumes:
  pw-service-auth-data: