ktor:
    development: true
    deployment:
        port: 5050
        watch:
          - classes
          - resources
    application:
        modules:
          - site.pets.world.ApplicationKt.module