name: Init administrators in DB

on:
#  push:
#    branches:
#      - 'mongodb_init'
#    paths:
#      - 'mongo/**'
  workflow_dispatch:


env:
  env:
    REGISTRY: ghcr.io
    ORGANISATION: petsworld-ltd
    IMAGE_NAME: pw-service-auth-mongodb-init

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app's image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORGANISATION }}/${{ env.IMAGE_NAME }}:latest

      - name: Launch administrator collection initialization
        uses: appleboy/ssh-action@v0.1.8
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.ORGANISATION }}/${{ env.IMAGE_NAME }}:latest
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASS: ${{ secrets.MONGODB_PASS }}
        with:
          host: ${{ secrets.TARGET_SERVER }}
          username: ${{ secrets.TARGET_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: MONGODB_USER,MONGODB_PASS
          port: 22
          script: |
            docker image prune
            docker rm -f mongodb_init
            docker pull $IMAGE
            docker run -e MONGODB_USER=$MONGODB_USER -e MONGODB_PASS=$MONGODB_PASS -e MONGODB_ADDRESS=localhost:27017  --name mongodb_init $IMAGE
